spring:
  # H2 Database Setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:

  # H2 Console Setting
  h2:
    console:
      enabled: true           # H2 Console available
      path: /h2-console       # H2 Console address

  # JPA Setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# JWT Setting
jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-HS256-algorithm-security
  access-token-expiration: 1800000    # 30 minute
  refresh-token-expiration: 604800000 # 7 days
